### PR TITLE
🧣 Add class_overall_average

### PR DESCRIPTION
**Pull request by lucas-luchack**
I have done all the following:

- [x] added the feature
- [x] added documentation for the feature
- [x] added tests for the feature
- [x] ran mypy, black, and unit tests

Also add calculating for class average

### CODE REVIEW

**Comment by bain3** [comment]
Hi, thanks, but it duplicates [`Period.group_average`](https://pronotepy.readthedocs.io/en/latest/api/data.html#pronotepy.Period.group_average). I guess it should be renamed to `Period.class_overall_average`.

**Comment by lucas-luchack** [comment]
It's not a dublicate, my function calculate the class average if none is provided by Pronote. (I said it in my PR comment)

**Comment by bain3** [comment]
I don't think we want to provide values calculated by ourselves. Even the `Period.overall_average` will have it removed at some point. It is an API wrapper... right? Pronotepy should be bridge, and if the value is not on pronote directly, then we should return that reality.

Removing this from `Period.overall_average` would be a breaking change, so it has to stay until `v3`.

**Comment by bain3** [comment]
I am going to rename `Period.group_average` to `Period.class_overall_average`.

**Comment by lucas-luchack** [comment]
Okay, thanks for your explanation!

**Pull request closed without merging**
