### PR TITLE
put ENT tests into subtests and run in parallel

### PR DESCRIPTION
**Pull request by bain3**

### CODE REVIEW

**Comment by bain3** [comment]
So this is kinda weird... I'm not sure about the others, but `ac_orleans_tours` throws this ssl error only sometimes (when ran manually). `ac_rennes` errors out consistently though.

**Comment by Bapt5** [comment]
I didn't see the error on AC Rennes

**Comment by bain3** [comment]
I think most `ConnectionError`s are from IP bans. I don't know if we want the functions to raise them, or replace them with `ENTLoginError`s though...

**Comment by bain3** [comment]
> So this is kinda weird... I'm not sure about the others, but `ac_orleans_tours` throws this ssl error only sometimes (when ran manually). `ac_rennes` errors out consistently though.

CORRECTION: Even `ac_rennes` raises the `ConnectionError` just sometimes. I really think they are VPN bans / temporary IP bans.

**Comment by Bapt5** [comment]
@bain3 I think that we can merge this PR, if everything is ready for you.

**Pull request merged**
