### PR TITLE
Fix Lycée Connecté (Nouvelle-Aquitaine) ENT

### PR DESCRIPTION
**Pull request by lucas-luchack**
The URL for Lycée Connecté was wrong, the right URL is `https://mon.lyceeconnecte.fr/`

### CODE REVIEW

**Comment by Bapt5** [comment]
You're right the URL must have changed since I implemented this ENT.

**Comment by Bapt5** [comment]
Can you format your change with the command `black pronotepy` in the folder of your repository please

**Comment by lucas-luchack** [comment]
> Can you format your change with the command `black pronotepy` in the folder of your repository please 

Sure!

**Comment by lucas-luchack** [comment]
It's done!

**Pull request merged**
