### PR TITLE
current_period match against current date

### PR DESCRIPTION
**Pull request by pelrol**
For some reason, the current period was the 'Trimestre 1', I figured out how to identify correctly the current period thanks to https://github.com/Vexcited/pornote/blob/2f3b4f79b4be1cb708c9061710eb683a3917aa50/packages/web/src/utils/client.ts#L865

As simple as looking for period matching current date.

### CODE REVIEW

**Comment by bain3** [comment]
Sometimes PRONOTES have multiple types of periods that overlap (trimesters, semesters)... I'm not sure if this method will always return the correct one...

**Comment by pelrol** [comment]
Good point, did not know about this.
In this case we could maybe add another method to return the first period matching the current date, and so let the user choose.

**Comment by Bapt5** [comment]
I think pronotepy should only provide the info given by Pronote.  In this case Pronote provides the current period (it works very well for me).  If this period is not the one the user wants, nothing prevents him from doing a function similar to yours to obtain the period.

**Comment by pelrol** [comment]
This was my point, the current_period did not work for me (returning 'Trimestre 1' instead of 'Trimestre 2') although the pronote Android application did have the correct period selected for grades.
Maybe someone could investigate with me for one of my accounts to check if it's a bug or not in pronotepy.
What's needed to investigate ?

**Comment by bain3** [comment]
I think I know what is going on. Looking at the javascript, the client does indeed get the current period from the same place as we do, but it can change depending on the onglet open (we just pick it from the first from the list). We could try to assume that 198 is the "mes notes" onglet and always take from that, otherwise default to the first one.

**Comment by bain3** [comment]
Done! Thanks for pointing this error out!

**Pull request closed without merging**
