### PR TITLE
Add Pronote Educonnect login

### PR DESCRIPTION
**Pull request by lucas-luchack**
I have done all the following:

- [x] added the feature
- [x] added documentation for the feature
- [x] added tests for the feature
- [x] ran mypy, black, and unit tests

### CODE REVIEW

**Comment by andronedev** [comment]
C'est top 👍

**Comment by lucas-luchack** [comment]
Yes, it's because it need the service URL to a pronote server

**Comment by Bapt5** [comment]
I don't understand because normally the connection through Educonnect is done with the dedicated `educonnect` function. Can you give me a specific example where this function is used ?

**Comment by lucas-luchack** [comment]
Take exemple with this establishment (it's not mine) :
> https://0332283c.index-education.net/pronote/

If you click on student it's redirecting the user to educonnect for login, and this "ENT" (hubeduconnect) is not implemented, or i didn't find it...

**Comment by Bapt5** [comment]
Okay I understand. Can you rename your fonction by `pronote_hubeduconnect` for example to make it more understandable. 
Are you sure it's work even if the service GET argument is not provide as you do in the function ?

**Comment by lucas-luchack** [comment]
Huh, let me check...

**Comment by bain3** [comment]
So does the ENT work? I'd like to merge it :)

**Comment by lucas-luchack** [comment]
It seems that yes if we provide the function with the url of the establishment

**Comment by bain3** [comment]
We'll see

**Pull request merged**
