### PR TITLE
ENT rework

### PR DESCRIPTION
**Pull request by Bapt5**
* add all NG ENT Open #103
* use educonnect fonction for all educonnect authentification (#67 #40 #100)
*  fix occitanie (#62)
* ENT rework #56 
* add ENT Eclat BFC #65 
* add CAS Agora #108

### CODE REVIEW

**Comment by Bapt5** [comment]
I have the project to add all the ENT of France in a short time.

**Comment by bain3** [comment]
I hope you meant this was still WIP, otherwise tell me.

**Comment by Bapt5** [comment]
Not all commits are ready I will add the others ENT later in another pull request

**Comment by 0xTxm** [comment]
Hi @Bapt5 I lost all my code when I changed pc, but I had the idea of making a python implementation of that for the ENTs, never had a chance to finish it though : https://github.com/3l0w/pronote-api (look at forks as the main repo got taken down)

But in there you basically have all the ENTs already implemented for you in JS. Hope it helps on your journey :)

**Review by bain3 — APPROVED** [review]
I guess LGTM. Much cleaner than it was. Sadly we don't have a way to test it but I think it's worth merging and fixing the issues afterwards.

**Comment by Bapt5** [comment]
@0xTxm thanks a lot I already knew this API.  It s awesome.  And I was planning to use it

**Comment by Bapt5** [comment]
> Je suppose LGTM. Beaucoup plus propre qu'il ne l'était. Malheureusement, nous n'avons aucun moyen de le tester, mais je pense que cela vaut la peine de fusionner et de résoudre les problèmes par la suite.

I tested all functions I can test. And I here to

**Pull request merged**
