### PR TITLE
Added ParisClasseNumerique support.

### PR DESCRIPTION
**Pull request by tarneaux**
I'm adding support for ParisClasseNumerique ENT.
[Run screenshot](https://ibb.co/CKDtptf)

### CODE REVIEW

**Comment by tarneaux** [comment]
(I'd also be interested in becoming maintainer because i'm using this library a lot. I'm now developing an ENT message getter)

**Review by bain3 — APPROVED** [review]
LGTM!

**Comment by bain3** [comment]
Hi, sorry for the delayed merge. Would you mind adding me on discord? (bain(#)5038) Just to discuss you being a maintainer, potentially discuss other things about pronotepy :)

**Comment by tarneaux** [comment]
No problem for the merge.
I sent a friend request.

**Pull request merged**
