### PR TITLE
Fixes bain3/pronotepy#165

### PR DESCRIPTION
**Pull request by lesensei**
This fixes authentication through `enc_hauts_de_seine`. Tested with parent and student logins.
Let me know if the coding style or anything else needs work before it can be merged.

### CODE REVIEW

**Comment by Bapt5** [comment]
Very hard to review because you change all !!! @lesensei Please do clean commit where only your changes appear

**Comment by Bapt5** [comment]
Can you say me where you have change something ?

**Review by Bapt5 — COMMENTED** [review]
Are you sure that your modification also work for `ozecollege_yvelines` function ? (at line 335)

**Comment by lesensei** [comment]
Thanks for your comments, @Bapt5 .
I'm sorry about the diff on github. It looks like vscode changed all whitespace characters (i'm guessing tabs to spaces or vice-versa) and local diffs where ignoring these changes so I didn't see them until after I made the pull-request...
You can filter out the whitespace changes on github by using the "cog" button in the "files changed" tab and checking the "hide whitespace" checkbox.
For the Yvelines Oze instance, I have unfortunately no way to test. However, since the Yvelines and Hauts-de-Seine services are basically run by the same technical teams, I'm willing to bet it works in the exact same way for both, and I believe I didn't introduce anything specific to the Hauts-de-Seine in my changes.
Let me know if I should resubmit after fixing the whitespace stuff.
Thanks again.

**Comment by lesensei** [comment]
I'm sorry. I reset my fork to solve the line-endings problem and it closed this pull-request. I should have seen it coming though. tell me if I should reopen another or if it needs to be tested for Yvelines as well before (in which case, I have no idea how I can do that).

**Comment by Bapt5** [comment]
You can create a new PR I think (and hope) it will work for Yvelines

**Pull request closed without merging**
